"""slug  Migration

Revision ID: 6f82a24a12ed
Revises: 7df81998db9a
Create Date: 2022-04-20 12:16:57.572943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f82a24a12ed'
down_revision = '7df81998db9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###
