"""added password field

Revision ID: 791467ffb84d
Revises: 
Create Date: 2022-04-16 16:08:36.295872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791467ffb84d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
